### ISSUE TITLE
Error: AxiosError: Request failed with status code 403

### ISSUE THREAD

**Issue by itsRVX** [PabloCodingg/cfx-api#21]
Trying to make a discord bot. keep getting this error. code and error are down below

Any help in fixing this would be very much appreciated <3

Error: AxiosError: Request failed with status code 403
TypeError: Cannot read properties of undefined (reading 'gameType')
```js
const { EmbedBuilder, SlashCommandBuilder } = require('discord.js')
const cfx_api = require('cfx-api');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('cfxinfo')
    .setDescription('pong!'),

  async execute(client, interaction,) {
    const cfx = await cfx_api.fetchServer(process.env.id);

    
    const Embed = new EmbedBuilder()
          .setTitle('Server Information')
          .addFields(
            {name: 'Gametype', value: `${cfx.gameType}`, inline: true},
            {name: 'Map', value: `${cfx.mapname}`, inline: true},
            {name: 'Owner', value: `[${cfx.ownerName}](${cfx.ownerProfileUrl})`, inline: true},
            {name: 'Player\'s', value: `${cfx.playersCountFromServerReport}`, inline: true},
            {name: 'UpVote', value: `${cfx.upvotePower}`, inline: true},
            {name: 'OneSync', value: `${cfx.isOneSyncEnabled}`, inline: true},
            {name: 'Server Full', value: `${cfx.isFull}`, inline: true},
            {name: 'Private', value: `${cfx.private ? 'Private' : 'Public'}`, inline: true},
          )

          interaction.reply({ embeds: [Embed]});
  }
}
```

**Comment by itsRVX** [comment]
Am I doing something wrong or is it out of my control?

**Comment by itsRVX** [comment]
any help?

**Comment by pstomi** [comment]
Same problem for me :(

**Comment by davicustv** [comment]
Same

**Comment by itsRVX** [comment]
@a9ex @PabloCodingg any help solving this error?

**Comment by a9ex** [comment]
Hi,
Can you test with the commit d018acc80cbf498fe2cfd48d55f7dd446ce5e297 ? Or any commit before November 15th?

**Comment by itsRVX** [comment]
> Can you test with the commit [d018acc](https://github.com/PabloCodingg/cfx-api/commit/d018acc80cbf498fe2cfd48d55f7dd446ce5e297) ? Or any commit before November 15th?

sure, how can i install that commit with npm? or do i need to manually switch the files

**Comment by itsRVX** [comment]
@a9ex i did npm install cfx-api@1.0.121
and i still got the same error

**Comment by itsRVX** [comment]
@a9ex i used all versions and they all seem broken

**Comment by itsRVX** [comment]
@a9ex @PabloCodingg any updates on this error or anymore things i cant test?

**Comment by itsRVX** [comment]
are there any specific intents or anything i need to enable?

**Comment by PabloCodingg** [comment]
Hello all,

The API seems to have some problems, I'll check what's going on and come back to you as soon as I fix it.

**Comment by pablo-1610** [comment]
Hello all,

The API seems to have some problems, I'll check what's going on and come back to you as soon as I fix it.
@itsRVX @pstomi @davicustv

**Comment by pablo-1610** [comment]
Update published !

**Comment by kurthuber-dev** [comment]
Hello all, 
I am currently also setting up a Discord bot with cfx-api and also get Error: AxiosError: Request failed with status code 403

Functions like cfx.fetchServer do not work
Are there currently problems with the api here?

**Comment by Ximaz** [comment]
> 

Hi, we're sorry to hear you're facing an issue with the API, may you provide the entire issue so that we can try to find a workaround ?

**Comment by kurthuber-dev** [comment]
> > 
> 
> Hi, we're sorry to hear you're facing an issue with the API, may you provide the entire issue so that we can try to find a workaround ?

Getting the following error message in my console:
Error: AxiosError: Request failed with status code 403

cfx.fetchServer I get nil value - undefined

**Comment by a9ex** [comment]
Which version are you on? Make sure you are above version 1.0.13 or commit 5536204f5413b1f84ac750085d17317525480e19

**Comment by kurthuber-dev** [comment]
ok i have fixed it thanks for the support
