### ISSUE TITLE
403 error when requesting information

### ISSUE THREAD

**Issue by Mryococo91** [PabloCodingg/cfx-api#87]
this piece of code requests the server name and displays it in the console

```
async function getServerName() {
    try {
        const server = await cfx.fetchServer(config.cfxCode);
        const serverName = server.data.hostname;
        console.log("Nom du serveur:", serverName);
    } catch (error) {
        console.error("Erreur lors de la récupération du nom du serveur:", error.message);
    }
}
```
but my console gives me a 403 error
and when I go to the url it returns a 404
I think the CFX_MASTERLIST url is no longer available (CfxApiRoutes.ts)

**Comment by Ximaz** [comment]
Hello, thank you for opening the issue. Can you provide us the `config.cfxCode` that you used to fetch the server in order for me to reproduce the bug ?

**Comment by Mryococo91** [comment]
cfxCode: "vjarme",

when I use the url directly in my web browser it works but I have no information when I use it in my code
https://servers-frontend.fivem.net/api/servers/single/vjarme

**Comment by Mryococo91** [comment]
even with the example in the readme it returns no information in my console

**Comment by Ximaz** [comment]
It has been fixed in the new push that you can find here : https://github.com/pablo-1610/cfx-api/commit/bd886330912a8e4ead2b72775c6ab1eec5061bf9

You may want to pull the project and re-run your code. The issue was a User-Agent value which cfx server was not able to parse anymore.
